// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNz9OqSW8FtX6_RFLpy1F_-8HcWEvoRTg',
    appId: '1:272104469888:web:633bcd2f57e3c8072cfd65',
    messagingSenderId: '272104469888',
    projectId: 'buzz-b274f',
    authDomain: 'buzz-b274f.firebaseapp.com',
    storageBucket: 'buzz-b274f.appspot.com',
    measurementId: 'G-K7VCCR93L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_CvfaLa2uJSz2N4c2cBRgeAMntPjGhdw',
    appId: '1:272104469888:android:3a8260f09409728d2cfd65',
    messagingSenderId: '272104469888',
    projectId: 'buzz-b274f',
    storageBucket: 'buzz-b274f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJZ-i34c4iVFkxeV0t2KS3HKZ-MbyPKt0',
    appId: '1:272104469888:ios:26fd65a69fe027c22cfd65',
    messagingSenderId: '272104469888',
    projectId: 'buzz-b274f',
    storageBucket: 'buzz-b274f.appspot.com',
    iosBundleId: 'com.example.buzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJZ-i34c4iVFkxeV0t2KS3HKZ-MbyPKt0',
    appId: '1:272104469888:ios:26fd65a69fe027c22cfd65',
    messagingSenderId: '272104469888',
    projectId: 'buzz-b274f',
    storageBucket: 'buzz-b274f.appspot.com',
    iosBundleId: 'com.example.buzz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNz9OqSW8FtX6_RFLpy1F_-8HcWEvoRTg',
    appId: '1:272104469888:web:63e317129c700a1a2cfd65',
    messagingSenderId: '272104469888',
    projectId: 'buzz-b274f',
    authDomain: 'buzz-b274f.firebaseapp.com',
    storageBucket: 'buzz-b274f.appspot.com',
    measurementId: 'G-8DNDMQSHX5',
  );
}
